version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql 

    
  adminer:
    image: adminer
    ports:
      - 8080:8080
      
volumes:
  mysql_data:





